const CONFIG = {
    titleWeb: "only th.tai042",
    introTitle: 'user th.tai042',
    introDesc: `1001 li do tai sao anh thich sieu nhan hong`,
    btnIntro: ':)))',
    title: 'Identity Verification',
    desc: 'choose the name of the person you hate',
    btnYes: 'Anh Ngoc',
    btnNo: 'other',
    question: 'Why do anh hate em?',
    btnReply: 'Gui cho ielts 11.0',
    reply: 'Dam bao nguoi yeu anh khong tat axit em :))',
    mess: 'Day la li do anh thich sieu nhan hong.',
    messDesc: 'Hen 05/09 - khai giang danh tay doi.',
    btnAccept: 'Thich thi chieu.',
    messLink: 'Dung la cham, den la don, ma ba do day ne mut.' //link mess của các bạn. VD: https://www.facebook.com/messages/t/100014188333536}
